###
# This vagrant configuration creates a simple VM, mounted at the
# given IP address, and executes the default puppet manifest against
# it.
###
Vagrant::Config.run do |config|

    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.network :hostonly, "192.168.56.11"

	# Note that the dierctory in the 3rd argument here should be the working directory on your host that
	# you wish to share to the virtual machine mounted at its /vagrant_development path
    config.vm.share_folder "v-development", "/vagrant_development", "../../"

    config.vm.provision :puppet

end
